/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as HealthRouteImport } from './routes/health'
import { Route as EmailMarketingRouteImport } from './routes/email-marketing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEmailMarketingRouteImport } from './routes/api/email-marketing'
import { Route as ApiContactRouteImport } from './routes/api/contact'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailMarketingRoute = EmailMarketingRouteImport.update({
  id: '/email-marketing',
  path: '/email-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailMarketingRoute = ApiEmailMarketingRouteImport.update({
  id: '/api/email-marketing',
  path: '/api/email-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email-marketing': typeof EmailMarketingRoute
  '/health': typeof HealthRoute
  '/healthz': typeof HealthzRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/api/email-marketing': typeof ApiEmailMarketingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-marketing': typeof EmailMarketingRoute
  '/health': typeof HealthRoute
  '/healthz': typeof HealthzRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/api/email-marketing': typeof ApiEmailMarketingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email-marketing': typeof EmailMarketingRoute
  '/health': typeof HealthRoute
  '/healthz': typeof HealthzRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/api/email-marketing': typeof ApiEmailMarketingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-marketing'
    | '/health'
    | '/healthz'
    | '/sitemap.xml'
    | '/api/contact'
    | '/api/email-marketing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-marketing'
    | '/health'
    | '/healthz'
    | '/sitemap.xml'
    | '/api/contact'
    | '/api/email-marketing'
  id:
    | '__root__'
    | '/'
    | '/email-marketing'
    | '/health'
    | '/healthz'
    | '/sitemap.xml'
    | '/api/contact'
    | '/api/email-marketing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailMarketingRoute: typeof EmailMarketingRoute
  HealthRoute: typeof HealthRoute
  HealthzRoute: typeof HealthzRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiEmailMarketingRoute: typeof ApiEmailMarketingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-marketing': {
      id: '/email-marketing'
      path: '/email-marketing'
      fullPath: '/email-marketing'
      preLoaderRoute: typeof EmailMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email-marketing': {
      id: '/api/email-marketing'
      path: '/api/email-marketing'
      fullPath: '/api/email-marketing'
      preLoaderRoute: typeof ApiEmailMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailMarketingRoute: EmailMarketingRoute,
  HealthRoute: HealthRoute,
  HealthzRoute: HealthzRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiContactRoute: ApiContactRoute,
  ApiEmailMarketingRoute: ApiEmailMarketingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
